version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
